### ISSUE TITLE
Error when finishing order

### ISSUE THREAD

**Issue by SebastianBotez** [mobilpay/Magento#1]
Hello, thank you for this plugin, unfortunatelly, I`m getting a javascript error when finishing my order.
See the attachment.
Some help or explanations would be appreciated. Thank you.
![untitled](https://cloud.githubusercontent.com/assets/10911720/20647462/7d53a540-b49d-11e6-8d55-1e63e9b6cbdb.png)

**Comment by andreipanait** [comment]
Hello @SebastianBotez .

What the error says is that the plug-in does not find the security keys. You need to make sure they are uploaded to your server in /app/code/local/Mobilpay/Cc/etc/certificates/ (you should have 2 .cer files and 2 .key files and it is important that you do not rename them).

Hope this helps.
