### ISSUE TITLE
Class 'Mobilpay_Payment_Request_Card' not found 

### ISSUE THREAD

**Issue by santoshsynapse** [mobilpay/Magento#11]
Fatal error: Uncaught Error: Class 'Mobilpay_Payment_Request_Card' not found in /home/uprj10212/www/app/code/Mobilpay/Credit/Block/Redirect.php:63 Stack trace: #0 /home/uprj10212/www/app/code/Mobilpay/Credit/view/frontend/templates/redirect.phtml(4): Mobilpay\Credit\Block\Redirect->getFormData() #1 /home/uprj10212/www/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/home/uprj10212...') #2 /home/uprj10212/www/lib/internal/Magento/Framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Mobilpay\Credit\Block\Redirect), '/home/uprj10212...', Array) #3 /home/uprj10212/www/lib/internal/Magento/Framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/home/uprj10212...') #4 /home/uprj10212/www/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml() #5 /home/uprj10212/www/lib/internal/Magento/Framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBl in /home/uprj10212/www/app/code/Mobilpay/Credit/Block/Redirect.php on line 63

**Comment by andreipanait** [comment]
See #9
