### ISSUE TITLE
Class 'Mobilpay_Payment_Request_Abstract' not found - compiling error

### ISSUE THREAD

**Issue by shuffless** [mobilpay/Magento#13]
After installing the following error appears at compilation (Mage 2.3.3, PHP 7.2/7.3)

```
$ bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 82.5 MiBPHP Fatal error:  Class 'Mobilpay_Payment_Request_Abstract' not found in public_html/app/code/Mobilpay/Credit/Mobilpay/Payment/Request/Sms.php on line 10
```

**Comment by navid59** [comment]
if you have the previous version of  MobilPay module and the V2.4 in same time,
Please disable the previous version & compile again.
Command to disable : bin/magento module:disable ModuleName

**Comment by shuffless** [comment]
It is a fresh install. The module would work well but not compile. I tried the 2.4 version as well which works up to the point where the conflict with other modules will appear.

**Comment by navid59** [comment]
1) Please, remove both module what you already installed .
2) Clear cache & Compile one time without MobilPay Module (make sure the cache is clear )
3) Regarding you have **Magento V2.3.3** get the module by using **git clone --single-branch --branch V2.3 https://github.com/mobilpay/Magento.git**
4) First do compile & make sure the MobilPay module is in your active module list
5) Set the configuration

**Comment by shuffless** [comment]
Thank you for your reply. 

I tried your suggestion for the clone as such

```
[master_frdhnpwjpu]:public_html$ git clone --single-branch --branch V2.3 https://github.com/mobilpay/Magento.git
Cloning into 'Magento'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 434 (delta 17), reused 92 (delta 14), pack-reused 333
Receiving objects: 100% (434/434), 116.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (103/103), done.
```

This will create a  `Magento/Modul\ Magento\ 2.3\ -\ Credit\ card/app/code/` folder where the git is cloned so I need to move the files to `/app/code/` using `mv Mobilpay/ ../../../../app/code/`

Ran  `bin/magento setup:upgrade` to get the module accounted for without errors. 

`bin/magento module:status` now includes in the module list the following

`Mobilpay_Credit`

ran `bin/magento c:c` to be sure everything is cleared

ran `bin/magento setup:di:compile` as indicated and got the following output:

 ```
bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 89.0 MiBPHP Warning:  Uncaught Exception: Warning: require_once(/home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/app/code/Mobilpay/Credit/Mobilpay/Payment/Request/Ntp/../Sms.php): failed to open stream: No such file or directory in /home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/app/code/Mobilpay/Credit/Mobilpay/Payment/Request/Ntp/Sms.php on line 11 in /home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/app/code/Mobilpay/Credit/Mobilpay/Payment/Request/Ntp/Sms.php(11): Magento\Framework\App\ErrorHandler->handler(2, 'require_once(/h...', '/home/489102.cl...', 11, Array)
#1 /home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/app/code/Mobilpay/Credit/Mobilpay/Payment/Request/Ntp/Sms.php(11): require_once()
#2 /home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(126): require_once('/home/489102.cl...')
#3 /home/489102.cloudwaysapps.com/v in /home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/vendor/magento/framework/App/ErrorHandler.php on line 61
PHP Fatal error:  Magento\Setup\Module\Di\Code\Reader\ClassesScanner::main(): Failed opening required '/home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/app/code/Mobilpay/Credit/Mobilpay/Payment/Request/Ntp/../Sms.php' (include_path='/home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/generated/code:/home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/generated/code:/home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/vendor/magento/zendframework1/library:.:/usr/share/php') in /home/489102.cloudwaysapps.com/vqpvkjmmdk/public_html/app/code/Mobilpay/Credit/Mobilpay/Payment/Request/Ntp/Sms.php on line 11
```


**Debug info:** 

Mage 2.3.3
PHP 7.3.23

**Comment by shuffless** [comment]
For the sake of the argument I did the same on a fresh new install of M2.3.3 where I only installed the module described by the process above and the error persists.

**Comment by shuffless** [comment]
The code in `app/code/Mobilpay/Credit/Mobilpay/Payment/Request/Ntp/Sms.php`  is looking for `Sms.php` that is missing in the parent folder `app/code/Mobilpay/Credit/Mobilpay/Payment/Request/`

```
require_once(__DIR__.'/../Sms.php');

class Mobilpay_Payment_Request_Ntp_Sms extends Mobilpay_Payment_Request_Sms
{
	function __construct()
	{
		parent::__construct();
	}
}
```


![image](https://user-images.githubusercontent.com/4831785/100102365-2d857a00-2e6c-11eb-9e3b-0a006eb1f5e1.png)

**Comment by shuffless** [comment]
Downloading the module from the Netopia Backend resulted in obtaining an archive with the missing file.

**Comment by shuffless** [comment]
Running the compile again resulted in getting the original error https://github.com/mobilpay/Magento/issues/13#issue-734456938

**Comment by navid59** [comment]
> Downloading the module from the Netopia Backend resulted in obtaining an archive with the missing file.
First of all sorry for late answering you

Is not need to be downloaded from previous module.
The SMS option is already removed for the new Magento Plugin .

The Branch V2.3 is updated with commenting line 11 in Mobilpay/Credit/Mobilpay/Payment/Request/Ntp/Sms.php.
Please, update form git / removing the "require_once(__DIR__.'/../Sms.php');"

Let us know if the problem during compile is solved 
Thx
