### ISSUE TITLE
Module is not compatible with Firecheckout 

### ISSUE THREAD

**Issue by shuffless** [mobilpay/Magento#14]
An undefined label is required for the modules to work. 

Tested with 
Magento 2.3.3 
PHP 7.3 
Firecheckout 1.24.1 (https://www.firecheckout.net/)

On various pages like order details or stores > configuration it pops the following error

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: label in vendor/magento/module-backend/Block/Widget/Grid/Column/Filter/Select.php on line 75

**Comment by navid59** [comment]
If you using Magento V2.3.3, please make sure you get the right module from branch v2.3

**Comment by shuffless** [comment]
Module for V2.3 needs fixes in both missing files and compilation errors as described in #16 and #13
