### ISSUE TITLE
Eroare la accesarea stores -> configuration

### ISSUE THREAD

**Issue by vdmcb** [mobilpay/Magento#15]
Urmatoarele erori apar dupa urmarea pasilor pentru instalarea modulului Netopia pe o instanta cu Magento 2.4.1.

**Pasi executati:**
1. `php bin/magento setup:upgrade`
2. `php bin/magento setup:static-content:deploy -f`
3. `php bin/magento ca:cl`

**Raspuns comanda `php bin/magento module:status`:**
```
...
Netopia_Netcard
...
```

**Erori la accesarea Stores -> Configuration:**

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/home/sh0p3d/public_html/app/code/Netopia/Netcard/etc/adminhtml/system.xml" is invalid:
Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 81

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 81

Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 87

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 87

Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 93

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 93

Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 99

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 99

Verify the XML and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/home/sh0p3d/public_html/app/code/Netopia/Netcard/etc/adminhtml/system.xml" is invalid:
Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 81

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 81

Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 87

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 87

Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 93

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 93

Element 'upload_dir': [facet 'pattern'] The value '' is not accepted by the pattern '([a-zA-Z0-9_]+/{0,1}){1,}'.
Line: 99

Element 'upload_dir': '' is not a valid value of the atomic type 'typeUploadDirRestriction'.
Line: 99

Verify the XML and try again.
<pre>#1 Magento\Framework\Config\Reader\Filesystem->read() called at [vendor/magento/framework/Config/Data/Scoped.php:119]
#2 Magento\Framework\Config\Data\Scoped->_loadScopedData() called at [vendor/magento/framework/Config/Data/Scoped.php:97]
#3 Magento\Framework\Config\Data\Scoped->get() called at [vendor/magento/module-config/Model/Config/Structure.php:127]
#4 Magento\Config\Model\Config\Structure->__construct() called at [generated/code/Magento/Config/Model/Config/Structure/Interceptor.php:14]
#5 Magento\Config\Model\Config\Structure\Interceptor->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#6 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]
#7 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#8 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:170]
#9 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276]
#10 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239]
#11 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]
#12 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]
#13 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#14 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/App/ActionFactory.php:44]
#15 Magento\Framework\App\ActionFactory->create() called at [vendor/magento/framework/App/Router/Base.php:306]
#16 Magento\Framework\App\Router\Base->matchAction() called at [vendor/magento/framework/App/Router/Base.php:167]
#17 Magento\Framework\App\Router\Base->match() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Magento\Backend\App\Router\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Magento\Backend\App\Router\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#20 Magento\Backend\App\Router\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/App/Router/Interceptor.php:23]
#21 Magento\Backend\App\Router\Interceptor->match() called at [vendor/magento/framework/App/FrontController.php:115]
#22 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#23 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#24 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#25 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#26 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#27 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#28 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#29 Magento\Framework\App\Bootstrap->run() called at [index.php:39]
</pre>

**Comment by shuffless** [comment]
Please try the solution described at #17 and let us know if you encounter a new error or not.

**Comment by navid59** [comment]
The solution is discussed at [#17](https://github.com/mobilpay/Magento/issues/17),
Also, the **upload_dir** currently removed from **system.xml**,
