### ISSUE TITLE
Git repository for Magento 2.3 is incomplete

### ISSUE THREAD

**Issue by shuffless** [mobilpay/Magento#16]
As described in #13 the repository is missing `app/code/Mobilpay/Credit/Mobilpay/Payment/Request/Sms.php` which can be obtained by downloading the archive from the Netopia website under implementation examples and then download the Magento code archive.

The archive still does not solve the compile error described in #13

**Comment by navid59** [comment]
First of all sorry for late answering you
The SMS option is already removed for the new Magento Plugin .

If  you used the Branch V2.3 , Please, update form git / removing the "require_once(DIR.'/../Sms.php');" from Mobilpay/Credit/Mobilpay/Payment/Request/Ntp/Sms.php at line #11

Let us know if the problem during compile is solved
Thx
