### ISSUE TITLE
Uncaught Error: Call to a member function setPreparedMessage() on null in 

### ISSUE THREAD

**Issue by filipac** [mobilpay/Magento#2]
It seems there is an issue with this line:
`$payment = $this->_order->getPayment();
$payment->setPreparedMessage($this->_objPmReq->objPmNotify->errorMessage);`

I get this error on payment confirmation:

> [16-Feb-2017 09:41:29 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setPreparedMessage() on null in /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php:330
> Stack trace:
> #0 /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php(90): Mobilpay\Credit\Controller\Cc\Ipn->_handleCapture()
> #1 /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php(51): Mobilpay\Credit\Controller\Cc\Ipn->_processNotification(Object(Mobilpay_Payment_Request_Card))
> #2 /webaccounts/magazi70/public_html/var/generation/Mobilpay/Credit/Controller/Cc/Ipn/Interceptor.php(24): Mobilpay\Credit\Controller\Cc\Ipn->execute()
> #3 /webaccounts/magazi70/public_html/vendor/magento/framework/App/Action/Action.php(102): Mobilpay\Credit\Controller\Cc\Ipn\Interceptor->execute()
> #4 /webaccounts/magazi70/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> #5 /webaccounts/magazi70/public_html/vendo in /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php on line 330
> [16-Feb-2017 09:41:32 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setPreparedMessage() on null in /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php:330
> Stack trace:
> #0 /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php(90): Mobilpay\Credit\Controller\Cc\Ipn->_handleCapture()
> #1 /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php(51): Mobilpay\Credit\Controller\Cc\Ipn->_processNotification(Object(Mobilpay_Payment_Request_Card))
> #2 /webaccounts/magazi70/public_html/var/generation/Mobilpay/Credit/Controller/Cc/Ipn/Interceptor.php(24): Mobilpay\Credit\Controller\Cc\Ipn->execute()
> #3 /webaccounts/magazi70/public_html/vendor/magento/framework/App/Action/Action.php(102): Mobilpay\Credit\Controller\Cc\Ipn\Interceptor->execute()
> #4 /webaccounts/magazi70/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> #5 /webaccounts/magazi70/public_html/vendo in /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php on line 330
> [16-Feb-2017 11:37:55 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setPreparedMessage() on null in /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php:222
> Stack trace:
> #0 /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php(111): Mobilpay\Credit\Controller\Cc\Ipn->_handlePaymentDenial()
> #1 /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php(51): Mobilpay\Credit\Controller\Cc\Ipn->_processNotification(Object(Mobilpay_Payment_Request_Card))
> #2 /webaccounts/magazi70/public_html/var/generation/Mobilpay/Credit/Controller/Cc/Ipn/Interceptor.php(24): Mobilpay\Credit\Controller\Cc\Ipn->execute()
> #3 /webaccounts/magazi70/public_html/vendor/magento/framework/App/Action/Action.php(102): Mobilpay\Credit\Controller\Cc\Ipn\Interceptor->execute()
> #4 /webaccounts/magazi70/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> #5 /webaccounts/magazi70/public_htm in /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php on line 222
> [16-Feb-2017 11:38:04 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setPreparedMessage() on null in /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php:222
> Stack trace:
> #0 /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php(111): Mobilpay\Credit\Controller\Cc\Ipn->_handlePaymentDenial()
> #1 /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php(51): Mobilpay\Credit\Controller\Cc\Ipn->_processNotification(Object(Mobilpay_Payment_Request_Card))
> #2 /webaccounts/magazi70/public_html/var/generation/Mobilpay/Credit/Controller/Cc/Ipn/Interceptor.php(24): Mobilpay\Credit\Controller\Cc\Ipn->execute()
> #3 /webaccounts/magazi70/public_html/vendor/magento/framework/App/Action/Action.php(102): Mobilpay\Credit\Controller\Cc\Ipn\Interceptor->execute()
> #4 /webaccounts/magazi70/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> #5 /webaccounts/magazi70/public_htm in /webaccounts/magazi70/public_html/app/code/Mobilpay/Credit/Controller/Cc/Ipn.php on line 222
>

**Comment by andreipanait** [comment]
We are unable to reproduce this error.

Please add var_dump($this->_objPmReq->objPmNotify->errorMessage); to Ipn.php just beneath line 222 (function _handlePaymentDenial()) and make a rejected order or resend the IPN for a rejected order.

Also, please use implementare@mobilPay.ro to direct your inquiries on this or any other problems. 

We will update this issue once we come up with the solution.

Thanks

**Comment by filipac** [comment]
The plugin does not work with Magento ver. 2.1.4

**Comment by andreipanait** [comment]
The plugin works fine with all Magento 2.x versions, 2.1.4 included

**Comment by filipac** [comment]
Your opinion. 2.1.4 is broken, 500 statuses. Even if payment is canceled, it redirects back to success page.

**Comment by andreipanait** [comment]
It's not an opinion, it's a fact. There is no such thing as a "success page" in mobilPay.

**Comment by filipac** [comment]
so, then, what is this page? 
`/mobilpaycredit/cc/success/?&orderId=97`

**Comment by andreipanait** [comment]
That is the returnURL and it's the same for accepted, pending or rejected payments.

`$objPmReqCard->returnUrl = $this->getUrl('mobilpaycredit/cc/success');`

Please use the repository to raise issues, highlight bugs and generally bring something to the table that might be useful for others coming here with similar issues. The fact that the plugin seems to crash on your server needs to be investigated and we are willing to help, but that is not to say that it does not work for others (see [here](http://csmage.digitalninja.ro) a work in progress integration)

**Comment by filipac** [comment]
@andreipanait i found a small issue (or big). What do you say about this change. After hours of debugging,
i found this line:
```php
$this->_order = $this->_orderFactory->loadByIncrementId((int)$order_id);
```

To fix the error 500 given above, i changed this line to:
```php
$this->_order = $this->_orderFactory->load((int)$order_id);
```

so **load** instead of **loadByIncrementId**.
I noticed that ```$order_id``` was for example 131, but increment_id in the database is 2000000089

That's why the order was not loaded ok and was returing null.

What do you say about this change?
The code works ok now, the invoice was created and the payment is now **complete**.
![screenshot from 2017-02-20 15-42-17](https://cloud.githubusercontent.com/assets/271155/23127299/303a9902-f783-11e6-9be6-15bbeddb89ee.png)

**Comment by andreipanait** [comment]
Well spotted. I would recommend you to test rejected payments as well and see how they are presented to the client in the returnURL (just press on Renunta in the payment page for the redirect to occur)

We actually used PayPal's IPN model, they use `loadByIncrementId ()` and it worked for us too, so that't that. We'd still like to investigate why it didn't work for you but it worked for us and several others. 

However, I can confirm it works with `load() `on our machines as well, so we'll update it accordingly (feel free to make a pull request on it if you'd like)

Thanks!

**Comment by filipac** [comment]
great! i will make a PR now. It also works for canceled orders too (also for insuficient funds and expired cc)
![screenshot from 2017-02-20 16-12-58](https://cloud.githubusercontent.com/assets/271155/23128412/8005d380-f787-11e6-9af0-1dfcc9ca4278.png)
