### ISSUE TITLE
Module for 2.4 does not show payment method description in checkout

### ISSUE THREAD

**Issue by shuffless** [mobilpay/Magento#20]
The payment method description set in the backend does not show up in the front end:

**Config:** 
![screenshot-m2 lamama ro-2020 12 08-12_28_06](https://user-images.githubusercontent.com/4831785/101472300-1c029e80-3951-11eb-85ed-0fd7f0925340.jpg)

**Result:** 
![screenshot-m2 lamama ro-2020 12 08-12_28_29](https://user-images.githubusercontent.com/4831785/101472321-24f37000-3951-11eb-8bc1-b3db2a592f91.jpg)

**Test setup:**
Mage 2.4.0
PHP 7.4
Redis
MariaDB 10.4

**Comment by navid59** [comment]
Thank you for mentioned this issue.
The Description is added to front-end.
Please, upgrade the module.
