### ISSUE TITLE
Upgraded code does not trigger redirect

### ISSUE THREAD

**Issue by shuffless** [mobilpay/Magento#21]
Upon page redirect the user is given this error:

"OOPS, something is wrong, you are not able to redirect into Payment page!"

Plugin version - latest from code repository
Mage 2.4.0
Php 7.4

**Comment by navid59** [comment]
Please, make sure you uploaded , correct Public & Private Keys
You have the keys in Netopia Admin panel.

**Comment by shuffless** [comment]
The update / upgrade guide might need a specification to reinstall certificates since the settings were in place from the previous code version. With all settings cleared and certificates reinstalled it works.
