### ISSUE TITLE
Despite payment error order is registered with "processing status"

### ISSUE THREAD

**Issue by shuffless** [mobilpay/Magento#22]
Despite getting and error described in #21 the order gets the "Processing" status

![screenshot-m2 lamama ro-2020 12 13-17_19_04](https://user-images.githubusercontent.com/4831785/102016020-78a5f500-3d67-11eb-9e7d-5027d821f4a3.jpg)

**Comment by shuffless** [comment]
Tested again with this scenario:
1. Add to cart
2. go to payment page
3. close payment page

The order goes in "processing" instead of cancelled or "pending payment"

**Comment by navid59** [comment]
This issue is already solved on issue nr #23
