### ISSUE TITLE
Unpaid order goes in processing instead of pending payment, paid order gets in complete state instead of processing

### ISSUE THREAD

**Issue by shuffless** [mobilpay/Magento#23]
_Note: I reverted the code from #21 because the new update is crashing the redirect._ 

Once the customer is redirected to the payment page (and payment is not yet made) the order is moved into **processing** state instead of **pending payment**: 

here the payment is still not completed

![screenshot--2020 12 13-18_16_37](https://user-images.githubusercontent.com/4831785/102017417-8a8b9600-3d6f-11eb-8279-659b2c9d3868.jpg)

Once the payment is processed successfully the order goes into **complete** state instead of **processing**:

![screenshot--2020 12 13-18_20_58](https://user-images.githubusercontent.com/4831785/102017502-05ed4780-3d70-11eb-9c1d-b675afb6ecb3.jpg)

The order log shows 2 "processing" triggers yet they are erroneous since the fist should have been pending payment. The 2'nd is correct yet it does not correspond to the order status:

![screenshot--2020 12 13-18_22_44](https://user-images.githubusercontent.com/4831785/102017533-42b93e80-3d70-11eb-9577-54c7f75d4087.jpg)

**Comment by shuffless** [comment]
One could also observe that the module does not have any configuration related to custom statuses, therefore the issue resides in the code and not in a configuration issue.

**Comment by shuffless** [comment]
The problem persists in latest code update

**Comment by navid59** [comment]
Yes, We working in this issue , and will inform you as soon as possible 
Thx

**Comment by shuffless** [comment]
Thank you. Looking fw to a fix.

**Comment by navid59** [comment]
Please, pull from git .
let us know if there is something else.
Thank you
