### ISSUE TITLE
Transaction record is registered as refund

### ISSUE THREAD

**Issue by shuffless** [mobilpay/Magento#24]
Once a successful payment is made the transaction is registered as refund not as a successful payment

![screenshot-o-2020 12 13-18_33_00](https://user-images.githubusercontent.com/4831785/102017810-c9bae680-3d71-11eb-8eb0-471e5bf83179.jpg)

![screenshot-2020 12 13-18_33_00 (1)](https://user-images.githubusercontent.com/4831785/102017813-cde70400-3d71-11eb-8296-6965c820a8b1.jpg)

**Comment by navid59** [comment]
In Issue #18 , is mentioned to PULL from GIT & upgrade the module .
DId you upgrade ? (Do clear catch after upgrade as well) 
Let us know if after upgrade you still have problem.

**Comment by shuffless** [comment]
The problem is solved in latest code update.
