### ISSUE TITLE
Ability to hide payment method over specific amount.

### ISSUE THREAD

**Issue by vdmcb** [mobilpay/Magento#26]
Is it possible to hide the payment method when the subtotal exceeds a specific amount? I see no "Minimum Order Total" / "Maximum Order Total" options after installing the plugin.

**Comment by navid59** [comment]
The plugin  works only with enabled / disabled options,  it's not in our roadmap to have an activation option based on other variables, like the cart total amount.

Based on your bank permitted limit, you can do the transaction by the plugin.
