### ISSUE TITLE
Order status remains Processing for a paid order with card via Mobilpay

### ISSUE THREAD

**Issue by sorinspanu** [mobilpay/Magento#27]
Hello,
Please help me with this issue on Magento 2.4.1

Order status is not updated from Processing to Completed when a user pays online via Mobilpay.

Here's the log

Feb 9, 2021 1:46:55 PM Processing Customer Notified
Feb 9, 2021 1:48:40 PM Pending Payment
Feb 9, 2021 1:48:40 PM Pending Payment
Feb 9, 2021 1:48:40 PM Invoice #0141199121 created

Notes for this Order
Tranzactia aprobata - Accepted by NETOPIA Payments - ID tranzacție: "************"
Comment added Feb 9, 2021 1:48:40 PM
Tranzactia aprobata Notificare înregistrata despre suma captata de 127,45 Lei. ID tranzacție: "**************"
Comment added Feb 9, 2021 1:48:40 PM

![payment-accepted-processing-status](https://user-images.githubusercontent.com/998478/107833556-572fac80-6d9c-11eb-95c5-6be20ddc3aa5.jpg)

**Comment by navid59** [comment]
Hello, 

It was this problem , but already solved.
- Please , make sure you have the latest update .
- Clean the cache (bin/magento c:c) / Remove the actual cache files
- Compile (bin/magento setup:di:compile)

Let us know if after this steps, you still have this problem.

**Comment by sorinspanu** [comment]
Hello,
Thank you for your answer.

I reinstalled the Mobilpay plugin with the latest version from github.
Recompiled and cleaned the cache ...

On order placed with credit card payment, I got this error:

![oja-latest-netopia](https://user-images.githubusercontent.com/998478/107874536-fb137800-6ec2-11eb-9172-c8ffdfd0a4c1.png)

I reverted back to the previous installed version. 
Do you have any insights on this?
Thanks

**Comment by navid59** [comment]
This problem, is because of your Private & Public Keys
1) Make sure the "Certification" folder has suitable permission
2) Upload the Keys from the Magento Admin section
