### ISSUE TITLE
Incorrect total amount is sent to payment gateway

### ISSUE THREAD

**Issue by shuffless** [mobilpay/Magento#28]
An incorrect total amount is sent to the gateway as such:

![cart subtotal](https://user-images.githubusercontent.com/4831785/109386348-cc55c280-7902-11eb-8a3a-658b1ad7db11.jpg)

![screenshot-sandboxsecure mobilpay ro-2021 02 27-13_52_49 (1)](https://user-images.githubusercontent.com/4831785/109386423-2b1b3c00-7903-11eb-91bf-dc7f15ccaab6.jpg)

Also sandbox SSL certificates are expired:

![screenshot-nimbus-capture-2021 02 27-13_51_46](https://user-images.githubusercontent.com/4831785/109386377-ff985180-7902-11eb-9b3a-36bdf2a4c2ea.jpg)

**Comment by shuffless** [comment]
Tested with various cart content combinations.

**Comment by shuffless** [comment]
A successful payment log is reflected differently in the message log and order totals.

![log](https://user-images.githubusercontent.com/4831785/109386530-dd530380-7903-11eb-951c-4dab7a13c5ab.jpg)

**Comment by navid59** [comment]
Please, let us know more detail about your Magento Website
- Is it an upgraded, module / is new Module 
- What is the Version of magento,
- .....

**Comment by shuffless** [comment]
Hi, 

I do not know when it appeared. We did some more test orders when these 2 aspects triggered:
1. SSL error
2. incorrect order amount

The issue appears on all products and it is not related to the type of product itself.

Thank you
