### ISSUE TITLE
A typo is present in the payment method description

### ISSUE THREAD

**Issue by shuffless** [mobilpay/Magento#29]
The typo resides in /app/code/Netopia/Netcard/view/frontend/web/template/payment/form.html

![typo 02 27-14_00_00](https://user-images.githubusercontent.com/4831785/109386557-1d19eb00-7904-11eb-9f03-ce514c557b99.jpg)

**Comment by shuffless** [comment]
For some reason neither i18n nor front-end translation tool can f
![](https://user-images.githubusercontent.com/4831785/109390367-e4850c00-7919-11eb-896b-d854840fe0f2.jpg)
ix this.

**Comment by navid59** [comment]
Is Updated and you are able to change the Translation from the following files
/i18n/en_US.csv
/i18n/ro_RO.csv
thx
