### ISSUE TITLE
Nice release

### ISSUE THREAD

**Issue by an4rei** [mobilpay/Magento#30]
that's sarcasm, besides all the typos, you even have var_dumps in your code

![image](https://user-images.githubusercontent.com/11984860/110670629-470dc000-81d6-11eb-98e7-1ea9742f127b.png)

Let us know when you're going to release the stable version. thanks!

**Comment by an4rei** [comment]
Also, the payPal copied button doesn't work

![image](https://user-images.githubusercontent.com/11984860/110671382-1aa67380-81d7-11eb-9865-5ac079b3ee3f.png)


I have to go ahead and edit styles to I see the hidden input fields in order to configure the plugin.

**Comment by an4rei** [comment]
![image](https://user-images.githubusercontent.com/11984860/110672066-df587480-81d7-11eb-89a0-4587d09e95f9.png)

???

**Comment by an4rei** [comment]
it goes into the default case because the status is pending_payment.

I have set 'Live' enabled and Debug to 'No' . The form still redirects to sandboxsecure and it doesn't update order status, it remains in pending_payment; I'm guessing the IPN is not working because of the Live/Debug setting?

When I disable Live and Enable debug, I get 
```
Error while loading X509 public key certificate! Reason:error:02001002:system library:fopen:No such file or directory error:2006D080:BIO routines:BIO_new_file:no such file error:
```
even though I have the keys uploaded(both sandbox and live)

**Comment by navid59** [comment]
> it goes into the default case because the status is pending_payment. (that's why the '!!!')

Except , some main payment statuses , user can see this message (!!!), when click on " Renunta" from payment page too.
Fill free to change the message in your own website
 
 IPN should work / working in both cases ( Live / Sandbox )
  for "X509 public key certificate!" make sure you have right permission also check the uploaded keys. 
 
 Recomand to after double check all your setting & permission , ... remove the cache & run compile  command.

**Comment by an4rei** [comment]
> > it goes into the default case because the status is pending_payment. (that's why the '!!!')
> 
> Except , some main payment statuses , user can see this message (!!!), when click on " Renunta" from payment page too.
> Fill free to change the message in your own website
> 
> IPN should work / working in both cases ( Live / Sandbox )
> for "X509 public key certificate!" make sure you have right permission also check the uploaded keys.
> 
> Recommend to after double check all your setting & permission , ... remove the cache & run compile command.


In my case I had used a sandbox card and proceeded with the payment in the sandbox environment. I did not click on 'renunta' in the payment page.

Regarding the public key certificate, in what folder do you upload the certificates? I will show you a picture that will contain the right permissions and the right files.


I've already tried your extension on two different magento 2.4 environments. Just go ahead and test your plugin, thanks!
