### ISSUE TITLE
Magento 2.2 - Exception when compiling

### ISSUE THREAD

**Issue by ervindobri** [mobilpay/Magento#31]
![image](https://user-images.githubusercontent.com/56959368/112289279-d5824700-8c96-11eb-8f54-02316292f997.png)

**Comment by navid59** [comment]
It's look's like you used the Plugin from Branch V2.3
Please, remove the current Module and install the module from branch MASTER

Let us know  if the problem is solved.
Thx

**Comment by ervindobri** [comment]
I used v2.2 plugin because as i stated in the title: ITS MAGENTO V2.2 not 2.4.

**Comment by navid59** [comment]
The Magento repository , Branch V2.2 is updated 
Please, update your app.
If you still have problem, Reopen the issue
