### ISSUE TITLE
This is so bad

### ISSUE THREAD

**Issue by andreif23** [mobilpay/Magento#32]
this module is bad in so many ways:
- object manager used all over the place
- "custom" log methods that try to write to a hardcoded path (not everybody uses /var/www/html as their website root)
- some custom controllers that replace checkout/succces. why?
- completely commented class Netopia/Netcard/Controller/Adminhtml/Tools/Xml.php
- test code commited \Netopia\Netcard\Controller\Payment\Status
- certificated stored in the module directory. since they're uploadable from admin it's supposed that that directory is writable when *it shouldn't be*. it represents a security risk!

and so many other things

I don't understand why would such a big company as Netopia publish such a bad module.

**Stop hiring juniors for modules that are dealing with payments please.**

**Comment by navid59** [comment]
Please, check the git then, reopen the issue
thx
