### ISSUE TITLE
Modul dependent de PayPal?

### ISSUE THREAD

**Issue by gondas33** [mobilpay/Magento#34]
In Netopia/Netcard/etc/adminhtml/di.xml este specificat                 
`<frontend_model>Magento\Paypal\Block\Adminhtml\System\Config\Fieldset\Payment</frontend_model>`

In cazul de fata, modulul PayPal este dezactivat/nu exista in composer

Nu pot activa/configura mobilpay-ul deloc din aceasta cauza:

![image](https://user-images.githubusercontent.com/11984860/219002880-994ba9c4-d553-4dee-bd0d-f7e87d2a7f1f.png)

@navid59

**Comment by navid59** [comment]
First of all thank you for mention this issue.
Is fixed , please update the plugin.

FYI:
The NETOPIA Payments plugin has no dependency on paypal module.
By default Magento use a method called "wipeButtonsConfiguration" for Configure buttons in payments modules ,...
So when we disable Paypal, this file is absent and we have this issue.
